### PR TITLE
Ms plot enhance

### LINKED ISSUE #31: MS_plot calling mis-documentation
Thanks for a great program! However, one always wants more...

I think there is a problem with the documentation for MS_plot when plotting one's own data, in terms of the forms of the matrices/vectors called. The document for how to plot your own observations on the stereonets for MS_plot says this:

   

>  MS_plot(..., 'sdata', azimuth, inclination, polarisation, avs)
>            Add data points to the P-wave velocity ('VP') or S-wave 
>            polarisation plot ('AVSPOL'), respectively. This can be used,
>            for example, to compare an elastic model with shear-wave
>            splitting measurements. In each case data points relate
>            to a ray propagating in a direction described by the azimuth 
>            and inclination. The point is coloured according to either 
>            the P-wave velocity, vp, or S-wave anisotropy, avs, in km/s
>            or %. In the case of S-wave anisotropy, the fast polarisation 
>            direction is also shown. _**Each argument (azimuth, inclination, 
>            vp, polarisation and avs) is an array and each must be the 
>            same length.**_

However, the program bombs if they are all the same 1xn or nx1 dimensions.  I found I needed to make the variables azimuth and inclination have the same dimensions, but polarisation and avs need to be the transpose, i.e. if azimuth and inclination are each 1xn, then polarisation and avs need to be nx1.

### PR DESCRIPTION
**Pull request by andreww**
Collected changes to MS_plot. These changes include:

* Adding stereographic projection (equal angle projection - i.e. on a Wulff net) with the new keyword 'stereo'. This is taken from pull request #32
* Add the ability to plot "bands" around each of the axes (e.g. to show the location of the SWS window). This adds the 'band' keyword that takes a vector of axis labels and a vector of angles. This is taken from pull request #26 
* Handle non-row-vector input for sdata and pdata. We "flatten" any input and turn it into a row vector (which is more or less what the documentation says). Input arguments just need the same number of elements. This addresses #31 

This pull request should close #31 #26 #32 and #15

### CODE REVIEW

**Comment by andreww** [comment]
@jwookey - does this look OK to you?

**Comment by jwookey** [comment]
Hi Andrew, 

Yeah, looks good. However I just recoded the MS_plot to include an equal area projection, and some framework so it’s a bit more consistent and we can add extra projections later if any occur to us (Mercator, perhaps!?). I changed the syntax in the process. 

I have pushed these changes up to a new branch (‘projection_options’) on my GH repo. Can you pull them from there?

Cheers,

James

**Comment by andreww** [comment]
Hi James,

I've added your commits from 'projection_options' here and made them work together with "bands" (which is nice - we can make a Wulff net, or a Schmidt net - but a bit messy). It would be good if you could take a look before I merge into master. 

One thing to double check is the fast shear wave directions for the lower hemisphere plots. For olivine these change a lot between upper and lower hemisphere plots, and I'm not sure this is correct. Everything else looks OK to me, but there are a large number of options and it's hard to test this graphical stuff.

Cheers,

Andrew

**Comment by jwookey** [comment]
You’re right, the fast directions are borked. Was testing with albite, it’s not so obvious and I convinced myself they were right. Leave it with me, I have Dave Mainprice’s original code to test against. 

James

**Comment by andreww** [comment]
Thanks - all looks good here to me. Shall I merge onto master?

**Comment by jwookey** [comment]
Might as well, sure. Default behaviour is unchanged, so should be uncontroversial. 

James

**Pull request merged**
